version: "3.9"
services:
  jaeger: 
    image: "jaegertracing/all-in-one:1.6"
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - jaeger-tutorial


networks:
  jaeger-tutorial:
    driver: bridge
     
