version: "3.9"
services:
  jaeger: 
    image: "jaegertracing/all-in-one:1.6"
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - jaeger-tutorial
  
  hotrod:
    image: "jaegertracing/example-hotrod:1.6"
    ports:
      - "8080-8083:8080-8083"
    command: ["-M", "-D", "100ms", "-W", "100", "all", "--jaeger-agent.host-port=jaeger:6831"]
    links:
      - "jaeger"
    networks:
      - jaeger-tutorial

networks:
  jaeger-tutorial:
    driver: bridge
     
